[GitHub Actions] Setup Tests via Github Actions (#561)
* creating test.yml

still need to add test changes for this to work

* testing addition of coveralls

* add coveralls token

* edit token

* edit token 2

* migrate to GitHub Actions secrets

* remove duplicate testing on push and PR

* Test new Coveralls set up

Using similar set up as to [here](https://github.com/marketplace/actions/coveralls-github-action)

* removing `flag-name` input

* Remove .coveralls.yml

* GA: Remove Python 3.6 from the build matrix

Otherwise, scipy returns this error during installation:
RuntimeError: Python version >= 3.7 required.

* GA: Use nose to run the tests

* Use AndreMiras' version of Coveralls action

According to https://github.com/coverallsapp/github-action/issues/4#issuecomment-727600521,
this version works, unlike the official https://github.com/marketplace/actions/coveralls-github-action.

* Remove .travis.yml

* Add relative_files = True in .coveragerc

* GA: Ignore Python 3.7 on Windows

* Remove unused coveralls lib

* Remove pytest

* Add comment for running performance test

Co-authored-by: Harvey Thompson <58153750+Harveyt47@users.noreply.github.com>
Co-authored-by: Matt McKay <mamckay@gmail.com>